services:
  web:
    image: registry.activitypub.software/transfem-org/sharkey:latest
    container_name: sharkey_web
    restart: unless-stopped

    labels:
      - "traefik.http.routers.sharkey.rule=Host(`fedi.gareth-coles.dev`)"
      - "traefik.http.routers.sharkey.entrypoints=websecure"
      - "traefik.http.routers.sharkey.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sharkey.service=sharkey"

      - "traefik.http.services.sharkey.loadbalancer.server.port=3000"
      - "traefik.http.services.sharkey.loadbalancer.server.scheme=http"

    depends_on:
      - db
      - redis
      - meilisearch

    networks:
      - web
      - sharkey

    environment:
      NODE_ENV: production

    volumes:
      - /srv/docker/gserv/sharkey/app/files:/sharkey/files
      - /srv/docker/gserv/sharkey/app/config:/sharkey/.config:ro
      - /srv/docker/gserv/sharkey/app/custom:/sharkey/custom:ro

    deploy:
      resources:
        limits:
          memory: 4096M

  redis:
    restart: unless-stopped
    image: docker.io/redis:7.0-alpine
    container_name: sharkey_redis

    networks:
      - sharkey

    volumes:
      - /srv/docker/gserv/sharkey/redis:/data

    deploy:
      resources:
        limits:
          memory: 200M

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.1.1

    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY

    networks:
      - sharkey

    volumes:
      - /srv/docker/gserv/sharkey/meili:/meili_data

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 2048M

  db:
    restart: unless-stopped
    image: postgres:17
    container_name: sharkey_db

    networks:
      - sharkey

    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

    volumes:
      - /srv/docker/gserv/sharkey/db:/var/lib/postgresql/data

    deploy:
      resources:
        limits:
          memory: 512M

networks:
  web:
    external: true

  sharkey:
    driver: bridge
    name: sharkey
