services:
  common:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped

    environment:
      - DB_TYPE=postgresdb

      - DB_POSTGRESDB_HOST=n8n-db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASS}

      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=n8n-redis
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}

    links:
      - n8n-db
      - n8n-redis

    volumes:
      - /srv/docker/gserv/n8n/data:/home/node/.n8n

    depends_on:
      n8n-db:
        condition: service_healthy

      n8n-redis:
        condition: service_healthy
