services:
  hanna-runner-dind:
    image: docker:dind
    container_name: "hanna-runner-dind"

    privileged: true
    hostname: hanna-runner-dind

    restart: "unless-stopped"

    volumes:
      - certs:/certs

  hanna-runner:
    image: "data.forgejo.org/forgejo/runner:6"
    container_name: "hanna-runner"

    command: "/gserv/scripts/container/forgejo-runner"
    restart: "unless-stopped"

    links:
      - hanna-runner-dind

    depends_on:
      hanna-runner-dind:
        condition: service_started

    environment:
      - DOCKER_HOST=tcp://hanna-runner-dind:2375
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client

      - FORGEJO_INSTANCE
      - RUNNER_NAME
      - RUNNER_TOKEN

    # User without root privileges, but with access to `./data`.
    user: 1001:1001

    volumes:
      - /srv/scripts:/gserv/scripts:ro
      - /srv/docker/hanna/runner/data:/data
      - certs:/certs

volumes:
  certs:
