services:
  gserv-runner-dind:
    image: docker:dind
    container_name: "gserv-runner-dind"
    privileged: true
    hostname: gserv-runner-dind

    restart: "unless-stopped"

    volumes:
      - certs:/certs

  gserv-runner:
    image: "data.forgejo.org/forgejo/runner:11"
    container_name: "gserv-runner"

    command: "forgejo-runner daemon"
    restart: "unless-stopped"

    links:
      - gserv-runner-dind

    depends_on:
      gserv-runner-dind:
        condition: service_started

    environment:
      DOCKER_HOST: tcp://gserv-runner-dind:2376
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client

    # User without root privileges, but with access to `./data`.
    user: 1001:1001

    volumes:
      - /srv/docker/gserv/runner/data:/data
      - certs:/certs

volumes:
  certs:
