services:
  feeds:
    image: freshrss/freshrss:latest
    container_name: feeds
    restart: unless-stopped

    logging:
      options:
        max-size: 10m

    networks:
      - web
      - feeds

    volumes:
      - /srv/docker/gserv/feeds/app/data:/var/www/FreshRSS/data
      - /srv/docker/gserv/feeds/app/extensions:/var/www/FreshRSS/extensions

      - /srv/docker/gserv/feeds/app/config.custom.php:/var/www/FreshRSS/data/config.custom.php
      - /srv/docker/gserv/feeds/app/config-user.custom.php:/var/www/FreshRSS/data/config-user.custom.php

    labels:
      # HTTP
      - "traefik.http.routers.feeds_http.entrypoints=web"
      - "traefik.http.routers.feeds_http.rule=Host(`feeds.gareth-coles.dev`)"
      - "traefik.http.routers.feeds_http.middlewares=https"
      - "traefik.http.middlewares.https.redirectscheme.scheme=https"

      # HTTPS
      - "traefik.http.routers.feeds.rule=Host(`feeds.gareth-coles.dev`)"
      - "traefik.http.routers.feeds.entrypoints=websecure"
      - "traefik.http.routers.feeds.tls.certresolver=letsencrypt"
      - "traefik.http.routers.feeds.service=feeds"

      # Load Balancer
      - "traefik.http.services.feeds.loadbalancer.server.port=80"
      - "traefik.http.services.feeds.loadbalancer.server.scheme=http"

    depends_on:
      - feeds-db
      - feeds-bridge

    environment:
      CRON_MIN: '12,39'
      LISTEN: 0.0.0.0:80
      OIDC_ENABLED: 0
      TRUSTED_PROXY: 172.0.0.0/8
      TZ: Europe/Dublin

  feeds-db:
    image: postgres:16
    container_name: feeds-db
    restart: unless-stopped

    shm_size: 128mb

    networks:
      - feeds

    volumes:
      - /srv/docker/gserv/feeds/app/db:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  feeds-bridge:
    image: rssbridge/rss-bridge:latest
    container_name: feeds-bridge
    restart: unless-stopped

    networks:
      - web
      - feeds

    volumes:
      - /srv/docker/gserv/feeds/bridge:/config

    labels:
      # HTTP
      - "traefik.http.routers.feeds-bridge_http.entrypoints=web"
      - "traefik.http.routers.feeds-bridge_http.rule=Host(`feeds-bridge.gareth-coles.dev`)"
      - "traefik.http.routers.feeds-bridge_http.middlewares=https"
      - "traefik.http.middlewares.https.redirectscheme.scheme=https"

      # HTTPS
      - "traefik.http.routers.feeds-bridge.rule=Host(`feeds-bridge.gareth-coles.dev`)"
      - "traefik.http.routers.feeds-bridge.entrypoints=websecure"
      - "traefik.http.routers.feeds-bridge.tls.certresolver=letsencrypt"
      - "traefik.http.routers.feeds-bridge.service=feeds-bridge"

      # Load Balancer
      - "traefik.http.services.feeds-bridge.loadbalancer.server.port=80"
      - "traefik.http.services.feeds-bridge.loadbalancer.server.scheme=http"

networks:
  web:
    external: true

  feeds:
    driver: bridge
    name: feeds
