services:
  gdude-git-runner-dind:
    image: docker:dind
    container_name: "gdude-git-runner-dind"

    privileged: true
    hostname: gdude-git-runner-dind

    restart: "unless-stopped"

    command:
      - "--insecure-registry"
      - "gserv-registry:5000"

    networks:
      - registry

    volumes:
      - certs:/certs

  gdude-git-runner:
    image: "data.forgejo.org/forgejo/runner:6"
    container_name: "gdude-git-runner"

    command: "/gserv/scripts/container/forgejo-runner"
    restart: "unless-stopped"

    networks:
      - registry

    links:
      - gdude-git-runner-dind

    depends_on:
      gdude-git-runner-dind:
        condition: service_started

    environment:
      - DOCKER_HOST=tcp://gdude-git-runner-dind:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client

      - FORGEJO_INSTANCE
      - RUNNER_NAME
      - RUNNER_TOKEN

    # User without root privileges, but with access to `./data`.
    user: 1001:1001

    volumes:
      - /srv/scripts:/gserv/scripts:ro
      - /srv/docker/gdude/git/runner/data:/data
      - certs:/certs

volumes:
  certs:

networks:
  registry:
    external: true
