services:
  mc-hoc:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true

    ports:
      - "25665:25565"
      - "25666:25566"

    environment:
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      DIFFICULTY: "2"
      ENABLE_COMMAND_BLOCK: "true"
      ENABLE_ROLLING_LOGS: "true"
      ENABLE_WHITELIST: "true"
      EULA: "TRUE"
      EXISTING_OPS_FILE: "MERGE"
      EXISTING_WHITELIST_FILE: "MERGE"
      HIDE_ONLINE_PLAYERS: "true"
      LOG_TIMESTAMP: "true"
      MAX_PLAYERS: "30"
      MEMORY: "10240M"
      MOTD: "House of Change"
      PREVENT_PROXY_CONNECTIONS: "true"
      PREVIEWS_CHAT: "true"
      SERVER_NAME: "House of Change"
      TZ: "Europe/Dublin"
      USE_MEOWICE_FLAGS: "true"
      USE_MODPACK_START_SCRIPT: "false"

      MODPACK_PLATFORM: "CURSEFORGE"

      CF_API_KEY: "${API_KEY}"
      CF_SERVER_MOD: "/modpacks/PACK_4.0.9.zip"

      CURSEFORGE_FILES: |-
        https://www.curseforge.com/minecraft/mc-mods/dcintegration/files/5332465

      OPS: |-
        1a07ce68-7eba-4609-909a-d6731a090138

      WHITELIST: |-
        1a07ce68-7eba-4609-909a-d6731a090138

    volumes:
      - "/srv/minecraft/house/server:/data"
      - "/srv/minecraft/house/downloads:/downloads"
      - "/srv/minecraft/house/modpacks:/modpacks"
