services:
  mc-hoc:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    restart: always

    ports:
      - "25665:25565"

    labels:
      # HTTP
      - "traefik.http.routers.mc-hoc-map_http.entrypoints=web"
      - "traefik.http.routers.mc-hoc-map_http.rule=Host(`mc-house.mercie.dev`)"
      - "traefik.http.routers.mc-hoc-map_http.middlewares=https"
      - "traefik.http.middlewares.https.redirectscheme.scheme=https"

      # HTTPS
      - "traefik.http.routers.mc-hoc-map.rule=Host(`mc-house.mercie.dev`)"
      - "traefik.http.routers.mc-hoc-map.entrypoints=websecure"
      - "traefik.http.routers.mc-hoc-map.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mc-hoc-map.service=mc-hoc-map"

      # Load Balancer
      - "traefik.http.services.mc-hoc-map.loadbalancer.server.port=25566"
      - "traefik.http.services.mc-hoc-map.loadbalancer.server.scheme=http"

    networks:
      - web

    environment:
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      DIFFICULTY: "2"
      ENABLE_COMMAND_BLOCK: "true"
      ENABLE_ROLLING_LOGS: "true"
      EULA: "TRUE"
      EXISTING_OPS_FILE: "MERGE"
      EXISTING_WHITELIST_FILE: "MERGE"
      FORGE_VERSION: "47.4.0"
      HIDE_ONLINE_PLAYERS: "true"
      LOG_TIMESTAMP: "true"
      MAX_PLAYERS: "30"
      MEMORY: "10240M"
      MOTD: "House of Change"
      PREVIEWS_CHAT: "true"
      SERVER_NAME: "House of Change"
      TYPE: "FORGE"
      TZ: "Europe/Dublin"
      USE_MEOWICE_FLAGS: "true"
      USE_MODPACK_START_SCRIPT: "false"
      PLAYER_IDLE_TIMEOUT: "15"
      VERSION: "1.20.1"

      CF_API_KEY: "${API_KEY}"

      CURSEFORGE_FILES: |-
        https://www.curseforge.com/minecraft/mc-mods/dcintegration/files/5332465

      MODRINTH_PROJECTS: |-
        bluemap:kC7iYqja
        nicknames:PDECWy8H
        auto-restart:nH7LrRhA

      OPS: |-
        1a07ce68-7eba-4609-909a-d6731a090138

      WHITELIST: |-
        1a07ce68-7eba-4609-909a-d6731a090138

      RCON_CMDS_STARTUP:  |-
        whitelist off

      RCON_CMDS_ON_CONNECT:  |-
        chunky pause

      RCON_CMDS_LAST_DISCONNECT:  |-
        chunky continue

    volumes:
      - "/srv/minecraft/house/server:/data"
      - "/srv/minecraft/house/downloads:/downloads"
      - "/srv/minecraft/house/modpacks:/modpacks"


networks:
  web:
    external: true
