services:
  mediawiki:
    build: .

    container_name: cmc_wiki
    restart: unless-stopped

    labels:
      # HTTP
      - "traefik.http.routers.cmc_wiki_http.entrypoints=web"
      - "traefik.http.routers.cmc_wiki_http.rule=Host(`moderation.wiki`)"
      - "traefik.http.routers.cmc_wiki_http.middlewares=https"
      - "traefik.http.middlewares.https.redirectscheme.scheme=https"

      # HTTPS
      - "traefik.http.routers.cmc_wiki.rule=Host(`moderation.wiki`)"
      - "traefik.http.routers.cmc_wiki.entrypoints=websecure"
      - "traefik.http.routers.cmc_wiki.tls.certresolver=letsencrypt"
      - "traefik.http.routers.cmc_wiki.service=cmc_wiki"

      # Load Balancer
      - "traefik.http.services.cmc_wiki.loadbalancer.server.port=80"
      - "traefik.http.services.cmc_wiki.loadbalancer.server.scheme=http"

    networks:
      - web
      - cmc-wiki

    depends_on:
      - database

    volumes:
      - /srv/docker/cmc/wiki/images:/var/www/html/images
    # - /srv/docker/cmc/wiki/LocalSettings.php:/var/www/html/LocalSettings.php

  database:
    image: mariadb:12

    container_name: cmc_wiki_db
    restart: unless-stopped

    networks:
      - cmc-wiki

    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MARIADB_RANDOM_ROOT_PASSWORD=1

    volumes:
      - /srv/docker/cmc/wiki/db:/var/lib/mysql

networks:
  cmc-wiki:
    driver: bridge
    name: cmc-wiki

  web:
    external: true
