services:
  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing

    networks:
      - web

    environment:
      - TZ=Europe/Dublin

    volumes:
      - /srv/docker/gserv/syncthing/config:/config
      - /srv/docker/gserv/syncthing/data:/mnt

    labels:
      - "traefik.http.routers.syncthing.rule=Host(`sync.gserv.me`)"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.tls.certresolver=letsencrypt"
      - "traefik.http.routers.syncthing.service=syncthing"

      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.http.services.syncthing.loadbalancer.server.scheme=http"

    restart: unless-stopped

    ports:
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"


networks:
  web:
    external: true
