services:
  rephasing-discord-bot:
    image: ghcr.io/rephas-ing/discord-bot:latest
    container_name: rephasing-discord-bot

    restart: always

    environment:
      - TOKEN

    volumes:
      - /srv/docker/rephasing/bots/discord/data:/bot/data
      - /srv/docker/rephasing/bots/discord/plugins:/bot/plugins
